apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: sausage-backend-sa
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dspring.cloud.vault.enabled=false -Dspring.config.import=optional:vault://kv/sausage-store"
            - name: SPRING_CLOUD_VAULT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_VAULT_HOST
              value: "localhost"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:vault://kv/sausage-store"
            - name: postgresUri
              value: jdbc:postgresql://postgresql:5432/sausage-store
            - name: reportPath
              value: /logs/reports
            - name: logPath
              value: /logs
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql:5432/sausage-store"
            - name: REPORT_PATH
              value: "/logs/reports"
            - name: LOG_PATH
              value: "/logs"
          envFrom:
            - secretRef:
                name: sausage-kv-secret
