apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sausage-kv-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
#    name: yandex-lockbox
#    kind: SecretStore
  target:
    name: sausage-kv-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ index .Values "sausage-store" "lockbox" "secret_id" }}
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ index .Values "sausage-store" "lockbox" "secret_id" }}
        property: password
    - secretKey: SPRING_DATA_MONGODB_URI
      remoteRef:
        key: {{ index .Values "sausage-store" "lockbox" "secret_id" }}
        property: mongo_uri
