apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-store-backend
  namespace: sausage-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sausage-store-backend
  template:
    metadata:
      labels:
        app: sausage-store-backend
    spec:
      serviceAccountName: sausage-backend-sa
      imagePullSecrets:
        - name: gitlab-pull-secret
      containers:
        - name: backend
          image: cloud-services-engineer.gitlab.yandexcloud.net:5050/s2633401/vigilia/sausage-frontend
          tag: latest
          env:
            - name: SPRING_CLOUD_VAULT_ENABLED
              value: "false"
            - name: SPRING_CONFIG_IMPORT
              value: ""
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sausage-kv-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sausage-kv-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: sausage-kv-secret
                  key: SPRING_DATA_MONGODB_URI
          ports:
            - containerPort: 8080
