apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sausage-store-frontend-ingress
  namespace: sausage-store
  annotations:
    gwin.yandex.cloud/groupName: "ingress"
    gwin.yandex.cloud/backend-protocol: "http"
    gwin.yandex.cloud/securityGroups: "enp7o89i6v83mr7tnemg"
    gwin.yandex.cloud/certificateId: "fpqhargr86st8fdmp74q"
spec:
  ingressClassName: "gwin-default"
  tls:
    - hosts:
        - "sausage-store.vigilia.site"
      secretName: "sausage-store-cert-secret" # any
  rules:
    - host: "sausage-store.vigilia.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sausage-store-frontend-service
                port:
                  number: 80
