apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sausage-store-yandex-ingress 
  annotations:
    "gwin.yandex.cloud/groupName": "sausage-store"
    "gwin.yandex.cloud/certificateId": "fpqhargr86st8fdmp74q"
    "gwin.yandex.cloud/backend-protocol": "http"
spec:
  ingressClassName: "gwin-default"
  rules:
    - host: "sausage-store.vigilia.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sausage-store-frontend-service
                port:
                  number: 80
