apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sausage-store-yandex-ingress
  namespace: sausage-store
  annotations:
    "gwin.yandex.cloud/groupName": "ingress"
    "gwin.yandex.cloud/externalIPv4Address": {{ .Values.ingress.gwin_ip | default "auto" | quote }}
    "gwin.yandex.cloud/securityGroups": {{ .Values.ingress.gwin_sg | quote }}
spec:
  ingressClassName: "gwin-default"
  tls:
    - hosts:
        - "sausage-store.vigilia.site"
      secretName: "yc-certmgr-cert-id-{{ .Values.ingress.certificate_id }}"
  rules:
    - host: "sausage-store.vigilia.site"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sausage-store-frontend-service
                port:
                  number: 80
