apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sausage-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://cloud-services-engineer.gitlab.yandexcloud.net/s2633401/vigilia.git"
    path: "deploy-yandex-cloud"
    targetRevision: "master"
    helm:
      releaseName: sausage-store
      valueFiles:
        - "values.yaml"
      values: |
        sausage-store:
          ingress:
            gwin_ip: {{ .Values.global.gwin_ip | quote }}
            gwin_sg: {{ .Values.global.gwin_sg | quote }}
            certificate_id: {{ .Values.global.certificate_id | quote }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "sausage-store"
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
