apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sausage-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://cloud-services-engineer.gitlab.yandexcloud.net/s2633401/vigilia.git"
    path: "deploy-yandex-cloud"
    targetRevision: "master"
    helm:
      parameters:
        - name: "ingress.gwin_ip"
          valueFrom:
            configMapKeyRef:
              name: infra-info
              key: gwin_ip
        - name: "ingress.gwin_sg"
          valueFrom:
            configMapKeyRef:
              name: infra-info
              key: gwin_sg
        - name: "ingress.certificate_id"
          valueFrom:
            configMapKeyRef:
              name: infra-info
              key: certificate_id
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "sausage-store"
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
