global:
  folder_id: ""
  monium_api_key: ""
  repo_url: ""
  gitlab_user: ""
  gitlab_token: ""
  gitlab_registry: ""
  eso_sa_id: ""
  lockbox_secret_id: ""
  gwin_ip: ""
  gwin_sg: ""
  certificate_id: ""
