apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repo_url | quote }}
    path: "yc/otel"
    targetRevision: "master"
    helm:
      values: |
        opentelemetry-kube-stack:
          gateway:
            replicaCount: {{ .Values.global.cluster_size | default 1 | int }}
            autoscaling:
              minReplicas: {{ .Values.global.cluster_size | default 1 | int }}
              maxReplicas: {{ mul (.Values.global.cluster_size | default 1 | int) 3 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: otel
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
