apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.107.2
  destination:
    server: https://kubernetes.default.svc
    # принцип минимальных привилегий
    namespace: otel
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
