apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    - repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
      chart: 'opentelemetry-kube-stack'
      targetRevision: 0.14.12
      helm:
        valueFiles:
          - $values/argocd-management/templates/observability/values.yaml
        parameters:
          - name: "global.monium_api_key"
            value: ""
          - name: "global.folder_id"
            value: ""
    - repoURL: {{ .Values.global.repo_url | quote }}
      targetRevision: master
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'otel'
  syncPolicy:
    automated:
      enabled: false
      # prune: false
      # selfHeal: false
    syncOptions:
      - CreateNamespace=true
