apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repo_url | quote }}
    path: "deploy-otel-yandex-cloud"
    targetRevision: "master"
    helm:
      values: |
        opentelemetry-collector:
          mode: deployment
          config:
            exporters:
              otlp:
                endpoint: "ingest.monium.yandex.cloud:443"
                headers:
                  "x-monium-project": "folder__{{ .Values.global.folder_id }}"
                  "Authorization": "Bearer {{ .Values.global.monium_api_key }}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "otel"
  syncPolicy:
    automated:
      enabled: false
