apiVersion: v1
kind: Secret
metadata:
  name: monium-secret
  namespace: otel
  annotations:
    argocd.argoproj.io/sync-wave: "4"
type: Opaque
stringData:
  api-key: "${global.monium_api_key}"
  folder-id: "${global.folder_id}"
  # api-key: {{ .Values.global.monium_api_key | quote }}
  # folder-id: {{ .Values.global.folder_id | quote }}
