sausage-store:
  global:
    imagePullPolicy: Always
    # секрет для скачивания образов
    imagePullSecrets:
      - name: gitlab-pull-secret
    vault:
      enabled: false
      host: ""

  lockbox:
    secret_id: ""

  ingress:
    host: "sausage-store.vigilia.site"
    gwin_ip: ""
    gwin_sg: ""
    certificate_id: ""

  frontend:
    ingress:
      host: sausage-store.vigilia.site
    imagePullSecrets:
      - name: gitlab-pull-secret
    image: cloud-services-engineer.gitlab.yandexcloud.net:5050/s2633401/vigilia/sausage-frontend
    tag: latest
    service:
      type: NodePort

  backend:
    imagePullSecrets:
      - name: gitlab-pull-secret
    image: cloud-services-engineer.gitlab.yandexcloud.net:5050/s2633401/vigilia/sausage-backend
    tag: latest
    extraEnv: []
    envFrom: []

  backend-report:
    imagePullSecrets:
      - name: gitlab-pull-secret
    image: cloud-services-engineer.gitlab.yandexcloud.net:5050/s2633401/vigilia/sausage-backend-report
    tag: latest

  infra:
    postgresql:
      containerPort: 5432
    mongodb:
      containerPort: 27017
