sausage-store:
  # 1. Секрет для скачивания образов
  global:
    imagePullSecrets:
      - name: gitlab-pull-secret

  # 2. Images
  frontend:
    image: cloud-services-engineer.gitlab.yandexcloud.net:5050/s2633401/vigilia/sausage-frontend
    service:
      type: NodePort
      port: 80

  backend:
    image: cloud-services-engineer.gitlab.yandexcloud.net:5050/s2633401/vigilia/sausage-backend
    service:
      type: ClusterIP 
      port: 8080

  backend-report:
    image: cloud-services-engineer.gitlab.yandexcloud.net:5050/s2633401/vigilia/sausage-backend-report
    service:
      type: ClusterIP
      port: 8080

  # 3. Ingress Gwin
  ingress:
    enabled: true
    ingressClassName: "gwin-default"
    annotations:
      "gwin.yandex.cloud/groupName": "sausage-store"
      "gwin.yandex.cloud/certificateId": "fpqhargr86st8fdmp74q"
      "gwin.yandex.cloud/backend-protocol": "http"
    hosts:
      - host: "sausage-store.vigilia.site"
        paths:
          - path: /
            pathType: Prefix
            component: frontend # Nginx
            port: 80
