stages:
  - tests
  - plan
  - apply
  - terratest
  - destroy
  - build
  - package
  - otel
  - performance

variables:
  TF_STATE_NAME: "tfstate"
  TF_HTTP_ADDRESS: "https://cloud-services-engineer.gitlab.yandexcloud.net/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}"
  TF_HTTP_LOCK_ADDRESS: "https://cloud-services-engineer.gitlab.yandexcloud.net/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}/lock"
  TF_HTTP_UNLOCK_ADDRESS: "https://cloud-services-engineer.gitlab.yandexcloud.net/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}/lock"
  TF_HTTP_USERNAME: "${GITLAB_USER_NAME}"
  TF_HTTP_LOCK_METHOD: "POST"
  TF_HTTP_UNLOCK_METHOD: "DELETE"
  TF_HTTP_RETRY_WAIT_MIN: "5"
  TF_LOG: INFO
  TF_VAR_cloud_id: ${CLOUD_ID}
  TF_VAR_folder_id: ${FOLDER_ID}
  TF_ROOT: ${CI_PROJECT_DIR}/infra
  PLAN: infra_plan.cache
  BTPLAN: bootstrap.tfplan
  GITLAB_ACCESS_TOKEN: ${TF_HTTP_PASSWORD}
  K6_BASE_URL: "sausage-store.${DOMAIN_NAME}"
  OPERATION:
    description: "Select CI/CD-operation"
    value: "terraform"
    options:
      - "terraform_bootstrap"
      - "terraform"
      - "pkg"
      - "otel"
  K6_VUS:
    value: "25"
    description: "Нагрузочное тестирование: количество виртуальных пользователей (VU)"
  K6_DURATION:
    value: "120"
    description: "Нагрузочное тестирование: длительность теста в секундах"
  ENABLE_TESTS:
    value: "true"
    options: ["true", "false"]
    description: "Запуск проверок и тестов"

# TEMPLATE FOR TERRAFORM JOBS ONLY
.terraform_setup:
  image: hashicorp/terraform:latest
  before_script:
    - cd ${TF_ROOT}
    - touch ./authorized_key.json && chmod 0600 ./authorized_key.json && echo ${AUTHORIZED_KEY} | base64 -d > ./authorized_key.json

.k6_setup:
  allow_failure: true
  script:
    - '[ "${ENABLE_TESTS}" == "false" ] && exit 0'
    - |
      docker run --rm \
        --user $(id -u):$(id -g) \
        -v "$(pwd)":/k6 \
        -w /k6 \
        grafana/k6:latest \
        run \
        --env K6_WEB_DASHBOARD=true \
        --env K6_WEB_DASHBOARD_EXPORT="${REPORT_NAME}.html" \
        --env TEST_RUN="${TEST_RUN}" \
        --env BASE_URL="${K6_BASE_URL}" \
        --env TEST_VUS="${K6_VUS}" \
        --env TEST_DURATION="${K6_DURATION}" \
        --out opentelemetry \
        --env K6_OTEL_GRPC_EXPORTER_ENDPOINT=ingest.monium.yandex.cloud:443 \
        --env K6_OTEL_EXPORTER_PROTOCOL=grpc \
        --env K6_OTEL_SERVICE_NAME="k6-loadtest-${REPORT_NAME}" \
        --env "K6_OTEL_HEADERS=authorization=Api-Key ${MONIUM_API_KEY},x-monium-project=folder__${FOLDER_ID}" \
        load-testing/load_test.js \
        --summary-export="${REPORT_NAME}.json"
  artifacts:
    reports:
      load_performance: "${REPORT_NAME}.json"
    paths: # https://grafana.com/docs/k6/latest/results-output/web-dashboard/
      - "${REPORT_NAME}.json"
      - "${REPORT_NAME}.html"

# Terraform plan для LE-сертификата
bootstrap_plan:
  extends: .terraform_setup
  stage: plan
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/infra/bootstrap
    TF_STATE_NAME: "btfstate"
  script:
    - terraform init
    - terraform fmt -check -recursive -diff || true
    - terraform validate
    - terraform plan -out=${BTPLAN}
    - terraform show -json ${BTPLAN} > ${BTPLAN}.json
  rules:
    - if: $OPERATION == "terraform_bootstrap" && $CI_COMMIT_BRANCH =~ /^(main|master)$/
      when: always
  artifacts:
    reports: # GitLab displays the details of the Terraform plan within the merge request widget.
      terraform: ${TF_ROOT}/${BTPLAN}.json
    paths:
      - ${TF_ROOT}/${BTPLAN}
      - ${TF_ROOT}/${BTPLAN}.json
    expire_in: 1 yrs

# Terraform cоздание LE-сертификата 
bootstrap_apply:
  extends: .terraform_setup
  stage: apply
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/infra/bootstrap
    TF_STATE_NAME: "btfstate"
  needs: ["bootstrap_plan"]
  script:
    - terraform init
    - terraform apply -auto-approve ${BTPLAN}
  rules:
    - if: $OPERATION == "terraform_bootstrap" && $CI_COMMIT_BRANCH =~ /^(main|master)$/
      when: manual
    - when: never

# Terraform удаление LE-сертификата
bootstrap_destroy:
  extends: .terraform_setup
  stage: destroy
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/infra/bootstrap
    TF_LOG: INFO
    TF_VAR_cloud_id: ${CLOUD_ID}
    TF_VAR_folder_id: ${FOLDER_ID}
  needs: ["bootstrap_apply"]    
  script:
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: $OPERATION == "terraform_bootstrap" && $CI_COMMIT_BRANCH =~ /^(main|master)$/
      when: manual
    - when: never


# Выполнение тестов checkov
checkov:
  stage: tests
  allow_failure: true
  image: bridgecrew/checkov:latest
  variables:
    GIT_DEPTH: "1"
  script:
    - '[ "${ENABLE_TESTS}" == "false" ] && exit 0'
    - checkov -d ${TF_ROOT} --external-checks-dir ${TF_ROOT}/custom_policies --output junitxml --output-file-path checkov_report
  artifacts:
    reports:
      junit: checkov_report/results_junitxml.xml
    paths:
      - checkov_report/
    expire_in: 8h
  rules:
    - if: $OPERATION == "terraform"
      changes:
        - "infra/**/*"
      when: always

# Выполнение cтатического анализа TFLint
tflint:
  extends: .terraform_setup
  stage: tests
  allow_failure: true
  variables:
    GIT_DEPTH: "1"
  script:
    - '[ "${ENABLE_TESTS}" == "false" ] && exit 0'
    - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | TFLINT_INSTALL_PATH="${TF_ROOT}" bash
    - terraform init -backend=false
    - ./tflint --init || true
    - mkdir -p ${CI_PROJECT_DIR}/tflint_report
    - ./tflint --recursive --format=junit > ${CI_PROJECT_DIR}/tflint_report/results_junit.xml || EXIT_CODE=$?
    - ./tflint --recursive --format=compact
    - exit ${EXIT_CODE:-0}
  artifacts:
    when: always
    reports:
      junit: tflint_report/results_junit.xml
    paths:
      - tflint_report/
    expire_in: 8h
  rules:
    - if: $OPERATION == "terraform"
      changes:
        - "infra/**/*"

# Terraform plan для инфраструктуры
plan:
  extends: .terraform_setup
  stage: plan
  needs: # не скачивать артифакты из tests
    - job: checkov
      artifacts: false
    - job: tflint
      artifacts: false 
  script:
    - terraform init
    - terraform fmt -check -recursive -diff || true
    - terraform validate
    - terraform plan -out=${PLAN}
    - terraform show -json ${PLAN} > tfplan.json
  rules:
    - if: $OPERATION == "terraform" && $CI_COMMIT_BRANCH =~ /^(main|master)$/
      changes:
        - "infra/**/*"
      when: always
  variables:
    TF_LOG: INFO
    TF_VAR_cloud_id: ${CLOUD_ID}
    TF_VAR_folder_id: ${FOLDER_ID}
    TF_VAR_vm_user: "${SSH_USER}"
    TF_VAR_ssh_key: "${SSH_PUBLIC_KEY}"
    TF_VAR_gitlab_username: ${ARGO_USER}
    TF_VAR_gitlab_token: ${ARGO_PASSWD}
    TF_VAR_argocd_admin_password: ${ARGO_ADM_PASSWD}    
    TF_VAR_spring_datasource_user: "${POSTGRES_USER}"
    TF_VAR_spring_datasource_pass: "${POSTGRES_PASSWORD}"
    TF_VAR_spring_mongo_uri: "${MONGODB_URI}"
  artifacts:
    reports: # GitLab displays the details of the Terraform plan within the merge request widget.
      terraform: ${TF_ROOT}/tfplan.json
    paths:
      - ${TF_ROOT}/${PLAN}
      - ${TF_ROOT}/tfplan.json
      - ${TF_ROOT}/.terraform/
    expire_in: 1 yrs

# Создание инфраструктуры Terraform
apply:
  extends: .terraform_setup
  stage: apply
  script:
    - terraform init
    - terraform apply -auto-approve ${PLAN}
    - echo "MONIUM_API_KEY=$(terraform output -raw monium_api_key)" >> ${CI_PROJECT_DIR}/monium.env
  rules:
    - if: $OPERATION == "terraform" && $CI_COMMIT_BRANCH =~ /^(main|master)$/
      changes:
        - "infra/**/*"
      when: manual
    - when: never
  variables:
    TF_LOG: INFO
    TF_VAR_cloud_id: ${CLOUD_ID}
    TF_VAR_folder_id: ${FOLDER_ID}
    TF_VAR_vm_user: "${SSH_USER}"
    TF_VAR_ssh_key: "${SSH_PUBLIC_KEY}"
    TF_VAR_gitlab_username: ${ARGO_USER}
    TF_VAR_gitlab_token: ${ARGO_PASSWD}
    TF_VAR_argocd_admin_password: ${ARGO_ADM_PASSWD}    
    TF_VAR_spring_datasource_user: "${POSTGRES_USER}"
    TF_VAR_spring_datasource_pass: "${POSTGRES_PASSWORD}"
    TF_VAR_spring_mongo_uri: "${MONGODB_URI}"
  artifacts:
    reports:
      dotenv: monium.env

# Удаление инфраструктуры Terraform за исключением LE-сертификата
destroy:
  extends: .terraform_setup
  stage: destroy
  script:
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: $OPERATION == "terraform" && $CI_COMMIT_BRANCH =~ /^(main|master)$/
      changes:
        - "infra/**/*"
      when: manual
    - when: never
  variables:
    TF_LOG: INFO
    TF_VAR_cloud_id: ${CLOUD_ID}
    TF_VAR_folder_id: ${FOLDER_ID}
    TF_VAR_vm_user: "${SSH_USER}"
    TF_VAR_ssh_key: "${SSH_PUBLIC_KEY}"
    TF_VAR_gitlab_username: ${ARGO_USER}
    TF_VAR_gitlab_token: ${ARGO_PASSWD}
    TF_VAR_argocd_admin_password: ${ARGO_ADM_PASSWD}    
    TF_VAR_spring_datasource_user: "${POSTGRES_USER}"
    TF_VAR_spring_datasource_pass: "${POSTGRES_PASSWORD}"
    TF_VAR_spring_mongo_uri: "${MONGODB_URI}"

# Выполнение тестов terratest
terratest:
  stage: terratest
  image: golang:1.21
  before_script:
    - cd ${TF_ROOT}
    - touch ./authorized_key.json && chmod 0600 ./authorized_key.json && echo ${AUTHORIZED_KEY} | base64 -d > ./authorized_key.json
  script:
    - '[ "${ENABLE_TESTS}" == "false" ] && exit 0'
    - cd test
    - go mod init terratest
    - go mod edit -go=1.21
    - go mod edit -require github.com/gruntwork-io/terratest@v0.46.16
    - go mod tidy
    - go test -v -timeout 10m || true
  needs:
    - job: apply
  dependencies:
    - apply
  rules:
    - if: $OPERATION == "terraform"
      changes:
        - "infra/**/*"
      when: on_success
  allow_failure: false
  variables:
    TF_LOG: INFO
    TF_VAR_cloud_id: ${CLOUD_ID}
    TF_VAR_folder_id: ${FOLDER_ID}
    TF_VAR_vm_user: "${SSH_USER}"
    TF_VAR_ssh_key: "${SSH_PUBLIC_KEY}"
    TF_VAR_gitlab_username: ${ARGO_USER}
    TF_VAR_gitlab_token: ${ARGO_PASSWD}
    TF_VAR_argocd_admin_password: ${ARGO_ADM_PASSWD}    
    TF_VAR_spring_datasource_user: "${POSTGRES_USER}"
    TF_VAR_spring_datasource_pass: "${POSTGRES_PASSWORD}"
    TF_VAR_spring_mongo_uri: "${MONGODB_URI}"

k6-pre-otel-loadtest:
  extends: .k6_setup
  stage: performance
  needs:
    - job: "apply"
      artifacts: true
    - job: "terratest"
  rules:
    - if: $OPERATION == "terraform"
      changes:
        - "infra/**/*"
      when: manual
  variables:
    REPORT_NAME: "report-pre"
    TEST_RUN: "pre"

# Сборка и пуш Docker-образов в GitLAB
build-and-push-images:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_IMAGE_BASE: $CI_REGISTRY_IMAGE
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg VERSION=$CI_COMMIT_SHA -t $DOCKER_IMAGE_BASE/sausage-backend:latest ./backend/
    - docker push $DOCKER_IMAGE_BASE/sausage-backend:latest
    - docker build -t $DOCKER_IMAGE_BASE/sausage-frontend:latest ./frontend/
    - docker push $DOCKER_IMAGE_BASE/sausage-frontend:latest
    - docker build -t $DOCKER_IMAGE_BASE/sausage-backend-report:latest ./backend-report/
    - docker push $DOCKER_IMAGE_BASE/sausage-backend-report:latest
  rules:
    - if: $OPERATION == "pkg"
      when: always

# Упаковка и пуш Helm-чарта в GitLAB
package-helm-chart:
  stage: package
  image: 
    name: alpine/helm:3.12.0
    entrypoint: [""]
  variables:
    HELM_PACKAGE_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
    HELM_OCI_REGISTRY: "oci://${CI_REGISTRY}/${CI_PROJECT_PATH}/charts"
  before_script:    
    - apk add curl
  script: # CI_PIPELINE_IID -internal ID that starts at 1 for each project and increments by 1 with every new pipeline
    - export CUR_VER=$(helm show chart ./sausage-store-chart/ | grep "^version:" | awk '{print $2}')
    - export NEW_VER=$(echo "$CUR_VER" | awk -F. -v iid="$CI_PIPELINE_IID" '{print $1"."$2"."iid}')
    - >
      sed -i -e "s/^version:.*$/version: $NEW_VER/" ./sausage-store-chart/Chart.yaml
    - echo $CI_JOB_TOKEN | helm registry login $CI_REGISTRY --username gitlab-ci-token --password-stdin
    - helm package ./sausage-store-chart/
    - helm push sausage-store-*.tgz $HELM_OCI_REGISTRY
  needs:
    - build-and-push-images
  rules:
    - if: $OPERATION == "pkg"
      when: manual
  tags:
    - docker


otel-apply:
  extends: .terraform_setup
  stage: apply
  script:
    - terraform init
    - echo "MONIUM_API_KEY=$(terraform output -raw monium_api_key)" >> ${CI_PROJECT_DIR}/monium.env
    - echo "ARGO_SERVER=$(terraform output -raw argocd_domain)" >> ${CI_PROJECT_DIR}/monium.env
  artifacts:
    reports:
      dotenv: monium.env
  rules:
    - if: $OPERATION == "otel"
      when: manual
  variables:
    TF_LOG: INFO

otel-activate:
  extends: .terraform_setup
  stage: otel
  image: argoproj/argocd:v2.8.4
  needs:
    - job: "otel-apply"
      artifacts: true
  script:
    - argocd login $ARGO_SERVER --username admin --password "${ARGO_ADM_PASSWD}" --grpc-web
    - >
      argocd app set argocd-management
      -p global.monium_api_key=$MONIUM_API_KEY 
      -p global.folder_id=$FOLDER_ID
    - >
      argocd app set otel-stack
      --sync-policy automated --auto-prune --self-heal
    - >
      argocd app set sausage-store 
      -p global.otel_enabled=true 
      -p global.folder_id=$FOLDER_ID
  rules:
    - if: $OPERATION == "otel"
      when: on_success

k6-post-otel-loadtest:
  extends: .k6_setup
  stage: performance
  needs:
  - job: "otel-apply"
    artifacts: true
  - job: "otel-activate"
  rules:
    - if: $OPERATION == "otel"
      when: manual
  variables:
    REPORT_NAME: "report-post"
    TEST_RUN: "post"
