all:
  hosts:
    app01:
      ansible_host: 10.10.10.10
      ansible_user: admin
      vm_type: app01
    mon01:
      ansible_host: 10.10.10.11
      ansible_user: admin
      vm_type: mon01
    prom01:
      ansible_host: 10.10.10.12
      ansible_user: admin
      vm_type: prom01
  vars:
