{{- if and .Values.global (eq (index .Values.global "otel_enabled" | toString) "true") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    instrumentation.opentelemetry.io/inject-sdk: "true"
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: sausage-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: sausage-store
    app.kubernetes.io/version: latest
    helm.sh/chart: frontend-0.1.0
  name: sausage-store-frontend
  namespace: sausage-store
{{- end }}
