apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend-ingress
  annotations:
    "gwin.yandex.cloud/groupName": "ingress"
    "gwin.yandex.cloud/externalIPv4Address": {{ index .Values "sausage-store" "ingress" "gwin_ip" | default "auto" | quote }}
    "gwin.yandex.cloud/securityGroups": {{ index .Values "sausage-store" "ingress" "gwin_sg" | quote }}
    {{- if ne (index .Values.global "otel_enabled" | toString) "false" }}
    instrumentation.opentelemetry.io/inject-sdk: "true"
    {{- end }}
spec:
  ingressClassName: "gwin-default"
  tls:
    - hosts:
        - {{ (index .Values "sausage-store").ingress.host | quote }}
      secretName: {{ printf "yc-certmgr-cert-id-%s" (index .Values "sausage-store" "ingress" "certificate_id") | quote }}
  rules:
    - host: {{ (index .Values "sausage-store").ingress.host | quote }}
      http:
        paths:
          - path: {{ (index .Values "sausage-store").ingress.path | default "/" }}
            pathType: {{ (index .Values "sausage-store").ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Release.Name }}-frontend-service
                port:
                  number: {{ (index .Values "sausage-store").frontend.service.port | default 80 }}
