apiVersion: v1
kind: Service
metadata:
  name: sausage-store-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      protocol: TCP
      targetPort: {{ .Values.service.port | default 8080 }}
