apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: sausage-store-instrumentation
  namespace: sausage-store
spec:
  exporter:
    endpoint: "http://otel-agent-collector.otel.svc.cluster.local:4317"
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
      value: "grpc"
  propagators:
    - tracecontext
    - baggage
  resource:
    attributes:
      - key: "service.name"
        value: "sausage-store"
      - key: "deployment.environment"
        value: "production"
      - key: "project"
        value: "folder__{{ .Values.global.folder_id }}"

  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  go: # https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/docs/configuration.md
    env:
      - name: OTEL_LOG_LEVEL
        value: "info"    
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: "grpc"
      - name: OTEL_GO_AUTO_INCLUDE_DB_STATEMENT
        value: "true"
      - name: OTEL_GO_AUTO_PARSE_DB_STATEMENT
        value: "true"
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest
  nginx:
    env:
      - name: OTEL_TRACES_EXPORTER
        value: otlp
    attrs:
    - name: NginxModuleOtelMaxQueueSize
      value: "4096"
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:latest
  sdk:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-sdk:latest
