apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: sausage-instrumentation
  namespace: sausage-store
spec:
  exporter:
    endpoint: http://otel-stack-daemon-collector.otel.svc.cluster.local:4317
  env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
  propagators:
    - tracecontext
    - baggage
  resource:
    attributes:
      - key: "service.name"
        value: "sausage-store"
      - key: "deployment.environment"
        value: "production"
      - key: "project"
        value: "folder__{{ .Values.global.folder_id }}"

  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  go:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:latest
  sdk:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-sdk:latest
