apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: yandex-lockbox
  namespace: sausage-store
spec:
  provider:
    yandexlockbox:
      auth:
        serviceAccountRef:
          name: sausage-backend-sa
