---
vault_port: 8200
vault_root_token: "my-root-token"

vault_host_config_path: "/etc/vault"
vault_host_data_path: "/var/lib/vault/data"

vault_volumes:
  - "{{ vault_host_config_path }}:/vault/config"
  - "{{ vault_host_data_path }}:/vault/file"

# Секреты для sausage-store
spring_datasource_user: "sausage_0dmin"
spring_datasource_pass: "sausage_pass"
spring_mongo_uri: "mongodb://mongouser:mongopassword@mongodb:27017/sausage-store"
