opentelemetry-kube-stack:
  clusterName: sausage-store-cluster

  opentelemetry-operator:
    enabled: true
    manager:
      extraArgs:
        - --enable-nginx-instrumentation=true

  rbac: # k8sattributes
    create: true

  collectors:
    # Агент (DaemonSet) на каждой ноде кластера
    agent:
      enabled: true
      mode: daemonset
      fullnameOverride: "otel-agent"
      service:
        enabled: true
      # Пробрасываем порты на IP ноды
      ports:
        - name: otlp-grpc
          port: 4317
          hostPort: 4317
          appProtocol: grpc
          protocol: TCP
        - name: otlp-http
          port: 4318
          hostPort: 4318
          appProtocol: http
          protocol: TCP
      config:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
        exporters:
          # Агент пересылает данные на шлюз (gateway) внутри кластера
          otlp:
            endpoint: "otel-gateway-collector.otel.svc.cluster.local:4317"
            tls:
              insecure: true
        service:
          pipelines:
            metrics:
              receivers: [otlp]
              exporters: [otlp]
            traces:
              receivers: [otlp]
              exporters: [otlp]
            logs:
              receivers: [otlp]
              exporters: [otlp]

    # Центральный шлюз (Deployment) для отправки в облако
    gateway:
      enabled: true
      mode: deployment
      fullnameOverride: "otel-gateway"
      extraEnvs:
        - name: MONIUM_API_KEY
          value: "{{ .Values.global.monium_api_key }}"
        - name: MONIUM_FOLDER_ID
          value: "{{ .Values.global.folder_id }}"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      config:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
        processors:
          batch:
            send_batch_size: 1000
            timeout: 10s
          k8sattributes:
            extract:
              metadata: [k8s.pod.name, k8s.namespace.name, k8s.node.name]
        exporters:
          # Шлюз авторизуется и отправляет данные в Yandex Monitoring (Monium)
          otlp_grpc/monium:
            endpoint: "ingest.monium.yandex.cloud:443"
            compression: zstd
            headers:
              Authorization: "Api-Key ${env:MONIUM_API_KEY}"
              x-monium-project: "folder__${env:MONIUM_FOLDER_ID}"
            sending_queue:
              enabled: true
            # Настройки повторных попыток при ошибках
            retry_on_failure:
              enabled: true
              initial_interval: 5s
              max_interval: 30s
              max_elapsed_time: 300s
          debug:
            verbosity: detailed
        service:
          extensions: [health_check]
          pipelines:
            metrics:
              receivers: [ otlp ]
              processors: [ k8sattributes, batch ]
              exporters: [ otlp_grpc/monium, debug ]
            traces:
              receivers: [ otlp ]
              processors: [ k8sattributes, batch ]
              exporters: [ otlp_grpc/monium, debug ]
            logs:
              receivers: [ otlp ]
              exporters: [ otlp_grpc/monium, debug ]
        # Телеметрия самого OTel Collector
        telemetry:
          logs:
            level: info  # debug | info | warn | error    
          metrics:
            level: detailed  # none | basic | normal | detailed
            readers:
              - periodic:
                  interval: 60000
                  exporter:
                    otlp:
                      protocol: http/protobuf
                      endpoint: http://${env:MY_POD_IP}:4318

# Глобальные переменные чарта
global:
  folder_id: ""
  monium_api_key: ""
  otel_enabled: "true"
