opentelemetry-kube-stack:
  opentelemetry-operator:
    enabled: true
    admissionWebhooks:
      certManager:
        enabled: true

  opentelemetry-collector:
    enabled: true
    fullnameOverride: "otel-collector" # Короткое DNS имя
    image:
      repository: "otel/opentelemetry-collector-k8s"
      tag: "0.110.0"
    
    mode: deployment

    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"


      processors:
        # Передает кумулятивные монотонные суммы как дельты, которые в Monium дифференцируются и пишутся с типом RATE. Требует дистрибутив otel-collector-contrib
        # cumulativetodelta:

        # Memory Limiter - защита от Out-of-Memory, рекомендуется в production для стабильности
        memory_limiter:
          check_interval: 1s
          limit_mib: 512        # Жесткий лимит памяти
          spike_limit_mib: 128  # Запас для всплесков

      exporters:
        otlp_grpc/monium:
          endpoint: "ingest.monium.yandex.cloud:443"
          compression: zstd
          headers:
            "x-monium-project": "folder__{{ .Values.global.folder_id }}"
            "Authorization": "Api-Key {{ .Values.global.monium_api_key }}"
          sending_queue:
            enabled: true
        
        logging:
          verbosity: normal

      service:
        pipelines:
          metrics:
            receivers: [otlp]
            exporters: [otlp_grpc/monium, logging]
          traces:
            receivers: [otlp]
            exporters: [otlp_grpc/monium, logging]
          logs:
            receivers: [otlp]
            exporters: [otlp_grpc/monium, logging]

        # Телеметрия самого OTel Collector
        telemetry:
          logs:
            level: info  # debug | info | warn | error    
          metrics:
            level: detailed  # none | basic | normal | detailed
            
            # Отправка телеметрии самого OTel Collector
            readers:
              - periodic:
                  interval: 60000
                  exporter:
                    otlp:
                      protocol: http/protobuf
                      endpoint: http://${env:MY_POD_IP}:4318



global:
  folder_id: ""
  monium_api_key: ""
  otel_enabled: false
