---
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: latest # noqa package-latest
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest # noqa package-latest
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: >-
      deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename
      }} stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest # noqa package-latest
    update_cache: true

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add SSHUSER to docker group
  user:
    name: sshuser
    groups: docker
    append: yes
