opentelemetry-kube-stack:
  clusterName: sausage-store-cluster

  extraObjects: []
  commonEnv: []

  opentelemetry-operator:
    enabled: true
    manager:
      extraArgs:
        - --enable-go-instrumentation=true
        - --enable-nginx-instrumentation=true
  rbac: # k8sattributes
    create: true
  collectors:
    # Агент (DaemonSet) на каждой ноде кластера
    agent:
      enabled: true
      mode: daemonset
      fullnameOverride: "otel-agent"
      presets:
        logsCollection: # доступ к лог-файлам [/var/log/pods/*/*/*.log]
          enabled: true
          includeCollectorLogs: false # не собирать логи OTel
        hostMetrics:
          enabled: true # метрики CPU/RAM нод 
        kubernetesAttributes:
          enabled: true # k8s_attributes
          extractAllPodLabels: true
          extractAllPodAnnotations: true
      resources:
        limits:
          cpu: 400m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi
      image: # k8sattributes, transform, hostmetrics
        repository: otel/opentelemetry-collector-contrib
        tag: latest 
      service:
        # направлять трафик телеметрии pod'ов только локальному otel-agent
        internalTrafficPolicy: Local
      # Пробрасываем порты на IP ноды
      hostNetwork: false
      ports:
        - name: otlp-grpc
          port: 4317
          #hostPort: 4317
          appProtocol: grpc
          protocol: TCP
        - name: otlp-http
          port: 4318
          #hostPort: 4318
          appProtocol: http
          protocol: TCP
        - name: syslog-udp
          port: 54527
          #hostPort: 54527
          protocol: UDP
      config:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
              http:
                endpoint: "0.0.0.0:4318"
          syslog:
            udp:
              listen_address: "0.0.0.0:54527"
            protocol: rfc3164 # RFC3164 (BSD) или RFC5424 (IETF)
            operators: 
              - type: json_parser
                parse_from: body
                parse_to: attributes
                onError: drop
          filelog:
            operators:
              - type: container
              - type: regex_parser
                id: trace-id-parser
                regex: 'trace_id=(?P<trace_id>[a-f0-9]+)'
                parse_from: body
                if: 'body contains "trace_id="'
                on_error: drop
              - type: regex_parser
                id: span-id-parser
                regex: 'span_id=(?P<span_id>[a-f0-9]+)'
                parse_from: body
                if: 'body contains "span_id="'
                on_error: drop
                # Яндекс ALB добавляет request_id, оставляем для корреляции
              - type: regex_parser
                id: request-id-parser
                regex: 'request_id=(?P<request_id>[a-f0-9-]+)'
                parse_from: body
                if: 'body contains "request_id="'
                on_error: drop
        processors:
          memory_limiter:
            check_interval: 1s
            limit_percentage: 85
            spike_limit_percentage: 25
          batch:
            send_batch_size: 8192
            send_batch_max_size: 16384
            timeout: 2s
          transform/trace:
            log_statements:
              - context: log
                statements:
                  # Для корреляции TraceID/SpanID берём значения из временных атрибутов
                  - set(log.trace_id, TraceID(log.attributes["trace_id"])) where log.attributes["trace_id"] != nil
                  - set(log.span_id, SpanID(log.attributes["span_id"])) where log.attributes["span_id"] != nil
                  # Удаляем временные атрибуты
                  - delete_matching_keys(log.attributes, "^(trace_id|span_id)$")
        exporters:
          # Агент пересылает данные на шлюз (gateway) внутри кластера
          otlp_grpc:
            endpoint: "otel-gateway-collector:4317"
            tls:
              insecure: true
          debug:
            verbosity: normal
        service:
          pipelines:
            metrics:
              receivers: [otlp]
              processors: [memory_limiter, batch]
              exporters: [otlp_grpc]
            traces:
              receivers: [otlp]
              processors: [memory_limiter, batch]
              exporters: [otlp_grpc]
            logs:
              receivers: [otlp, syslog]
              processors: [memory_limiter, transform/trace, batch]
              exporters: [otlp_grpc]
    # Центральный шлюз (Deployment) для отправки в Monium
    gateway:
      enabled: true
      mode: deployment
      fullnameOverride: "otel-gateway"
      presets: # сбора агрегированных данных о состоянии всего кластера
        clusterMetrics: 
          enabled: true
      # ArgoCD перезапишет, должно бвть по 1й на каждую зону - у Яндекс 4 ДЦ
      replicaCount: 1
      service:
        annotations:
          # передавать трафик телеметрии зоны A внутри зоны A
          service.kubernetes.io/topology-mode: Auto
      autoscaling:
        enabled: true
        # minReplicas: 4
        # maxReplicas: 12
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      rollingUpdate: # сначала создать, потом удалить
        maxUnavailable: 0
        maxSurge: 1
      resources:
        limits:
          cpu: 800m
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 512Mi
      # мягкое ограничение по зонам
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway 
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: "otel-gateway"
      # мягкое ограничение - 1 под на 1 ноду
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: "otel-gateway"
              topologyKey: "kubernetes.io/hostname"
      env:
        - name: MONIUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: monium-secret
              key: api-key
        - name: MONIUM_FOLDER_ID
          valueFrom:
            secretKeyRef:
              name: monium-secret
              key: folder-id
      config:
        extensions:
          health_check:
            endpoint: 0.0.0.0:13133
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
              http:
                endpoint: "0.0.0.0:4318"
        processors:
          batch:
            send_batch_size: 8192
            send_batch_max_size: 16384
            timeout: 2s
          resourcedetection: # В Яндекс можно использовать 'system' для hostname
            detectors: [env, system] 
            timeout: 2s
            override: false
        exporters:
          # Шлюз авторизуется и отправляет данные в Яндекс Monium
          otlp_grpc/monium:
            endpoint: "ingest.monium.yandex.cloud:443"
            compression: zstd
            headers:
              Authorization: "Api-Key ${env:MONIUM_API_KEY}"
              x-monium-project: "folder__${env:MONIUM_FOLDER_ID}"
            sending_queue:
              enabled: true
              queue_size: 5000 # в спанах
            # Настройки повторных попыток при ошибках
            retry_on_failure:
              enabled: true
              initial_interval: 5s
              max_interval: 30s
              max_elapsed_time: 300s
          debug:
            verbosity: normal
        service:
          extensions: [health_check]
          pipelines:
            metrics:
              receivers: [ otlp ]
              processors: [ resourcedetection, batch ]
              exporters: [ otlp_grpc/monium ]
            traces:
              receivers: [ otlp ]
              processors: [ resourcedetection, batch ]
              exporters: [ otlp_grpc/monium ]
            logs:
              receivers: [ otlp ]
              processors: [ resourcedetection, batch ]
              exporters: [ otlp_grpc/monium ]
        # Телеметрия самого OTel Collector
        telemetry:
          logs:
            level: warn  # debug | info | warn | error
          metrics:
            level: normal  # none | basic | normal | detailed
            readers:
              - periodic:
                  interval: 60000
                  exporter:
                    otlp:
                      protocol: http/protobuf
                      endpoint: http://${env:MY_POD_IP}:4318

  instrumentation:
    enabled: true
    name: "sausage-store-instrumentation"
    exporter:
      endpoint: "http://otel-agent-collector.otel.svc.cluster.local:4317"
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: "grpc"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_BSP_MAX_QUEUE_SIZE
        value: "16384"
      - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
        value: "4096"
      - name: OTEL_BSP_SCHEDULE_DELAY
        value: "500"
      # Сэмплирование
      # - name: OTEL_TRACES_SAMPLER
      #   value: "parentbased_traceidratio"
      # - name: OTEL_TRACES_SAMPLER_ARG
      #   value: "0.2"
    propagators:
      - tracecontext
      - baggage
    resource:
      resourceAttributes:
        service.name: "sausage-store"
        deployment.environment: "production"
        project: "folder__{{ .Values.global.folder_id }}"
    java:
      image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    go: # https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/docs/configuration.md
      env:
        - name: OTEL_LOG_LEVEL
          value: "info"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: "grpc"
        - name: OTEL_GO_AUTO_INCLUDE_DB_STATEMENT
          value: "true"
        - name: OTEL_GO_AUTO_PARSE_DB_STATEMENT
          value: "true"
      image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest
    nginx:
      env:
        - name: OTEL_LOG_LEVEL
          value: "info"
      attrs:
      - name: NginxModuleOtelMaxQueueSize
        value: "16384"
      image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nginx:latest
    #  image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:latest
    # sdk:
    #   image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-sdk:latest

  opAMPBridge:
    enabled: false

# Глобальные переменные чарта
global:
  folder_id: ""
  monium_api_key: ""
