opentelemetry-kube-stack:
  clusterName: sausage-store-cluster

  opentelemetry-operator:
    enabled: true
    manager:
      extraArgs:
        - --enable-go-instrumentation=true
        - --enable-nginx-instrumentation=true

  rbac: # k8sattributes
    create: true

  commonEnv:
    - name: MONIUM_API_KEY
      valueFrom:
        secretKeyRef:
          name: monium-secret
          key: api-key
    - name: MONIUM_FOLDER_ID
      valueFrom:
        secretKeyRef:
          name: monium-secret
          key: folder-id

  collectors:
    # Агент (DaemonSet) на каждой ноде кластера
    agent:
      enabled: true
      mode: daemonset
      fullnameOverride: "otel-agent"
      image:
        repository: otel/opentelemetry-collector-contrib
        tag: latest 
      service:
        enabled: true
      # Пробрасываем порты на IP ноды
      hostNetwork: true
      ports:
        - name: otlp-grpc
          port: 4317
          hostPort: 4317
          appProtocol: grpc
          protocol: TCP
        - name: otlp-http
          port: 4318
          hostPort: 4318
          appProtocol: http
          protocol: TCP
        - name: syslog-udp
          port: 54527
          hostPort: 54527
          protocol: UDP
      config:
        receivers:
          otlp_grpc:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
              http: # для Go
                endpoint: "0.0.0.0:4318"
          syslog:
            udp:
              listen_address: "0.0.0.0:54527"
            protocol: rfc3164 # rfc3164 стандартный Syslog. rfc5424
            operators: # nginx шлёт JSON 
              - type: json_parser
                parse_from: body
                parse_to: attributes
                onError: drop
        processors:
          batch: {}
          k8sattributes:
            extract:
              metadata: [k8s.pod.name, k8s.namespace.name, k8s.node.name]
          transform/nginx:
            log_statements:
              - context: log
                conditions:
                  - attributes["appname"] == "frontend"
                statements:
                  - set(trace_id, TraceID(attributes["trace_id"])) where attributes["trace_id"] != nil
                  - set(span_id, SpanID(attributes["span_id"])) where attributes["span_id"] != nil
                  - set(resource.attributes["service.name"], attributes["appname"])
                  - set(body, attributes["request"]) where attributes["request"] != nil
                  - delete_matching_keys(attributes, "^(trace_id|span_id|parent_id|request|appname)$")
        exporters:
          # Агент пересылает данные на шлюз (gateway) внутри кластера
          otlp_grpc:
            endpoint: "otel-gateway-collector:4317"
            tls:
              insecure: true
          debug:
            verbosity: detailed
        service:
          pipelines:
            metrics:
              receivers: [otlp_grpc]
              exporters: [otlp_grpc]
            traces:
              receivers: [otlp_grpc]
              exporters: [otlp_grpc]
            logs:
              receivers: [otlp_grpc, syslog]
              processors: [k8sattributes, transform/nginx, batch]
              exporters: [otlp_grpc, debug]

    # Центральный шлюз (Deployment) для отправки в облако
    gateway:
      enabled: true
      mode: deployment
      fullnameOverride: "otel-gateway"
      service:
        enabled: true
        selector:
          app.kubernetes.io/name: "otel-gateway"
          app.kubernetes.io/instance: "otel-stack"
      env:
        - name: MONIUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: monium-secret
              key: api-key
        - name: MONIUM_FOLDER_ID
          valueFrom:
            secretKeyRef:
              name: monium-secret
              key: folder-id
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      config:
        extensions:
          health_check:
            endpoint: 0.0.0.0:13133
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
              http:
                endpoint: "0.0.0.0:4318"
        processors:
          batch:
            send_batch_size: 1000
            timeout: 10s
          k8sattributes:
            extract:
              metadata: [k8s.pod.name, k8s.namespace.name, k8s.node.name]
        exporters:
          # Шлюз авторизуется и отправляет данные в Yandex Monitoring (Monium)
          otlp_grpc/monium:
            endpoint: "ingest.monium.yandex.cloud:443"
            compression: zstd
            headers:
              Authorization: "Api-Key ${env:MONIUM_API_KEY}"
              x-monium-project: "folder__${env:MONIUM_FOLDER_ID}"
            sending_queue:
              enabled: true
            # Настройки повторных попыток при ошибках
            retry_on_failure:
              enabled: true
              initial_interval: 5s
              max_interval: 30s
              max_elapsed_time: 300s
          debug:
            verbosity: detailed
        service:
          extensions: [health_check]
          pipelines:
            metrics:
              receivers: [ otlp ]
              processors: [ k8sattributes, batch ]
              exporters: [ otlp_grpc/monium, debug ]
            traces:
              receivers: [ otlp ]
              processors: [ k8sattributes, batch ]
              exporters: [ otlp_grpc/monium, debug ]
            logs:
              receivers: [ otlp ]
              processors: [ k8sattributes, batch ]
              exporters: [ otlp_grpc/monium, debug ]
        # Телеметрия самого OTel Collector
        telemetry:
          logs:
            level: info  # debug | info | warn | error
          metrics:
            level: detailed  # none | basic | normal | detailed
            readers:
              - periodic:
                  interval: 60000
                  exporter:
                    otlp:
                      protocol: http/protobuf
                      endpoint: http://${env:MY_POD_IP}:4318

  instrumentation:
    enabled: true
    name: "sausage-store-instrumentation"
    exporter:
      endpoint: "http://otel-agent-collector.otel.svc.cluster.local:4317"
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: "grpc"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
    propagators:
      - tracecontext
      - baggage
    resource:
      resourceAttributes:
        service.name: "sausage-store"
        deployment.environment: "production"
        project: "folder__{{ .Values.global.folder_id }}"
    java:
      image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    go: # https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/docs/configuration.md
      env:
        - name: OTEL_LOG_LEVEL
          value: "info"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: "grpc"
        - name: OTEL_GO_AUTO_INCLUDE_DB_STATEMENT
          value: "true"
        - name: OTEL_GO_AUTO_PARSE_DB_STATEMENT
          value: "true"
      image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest
    nginx:
      env:
        - name: OTEL_LOG_LEVEL
          value: "info"
      attrs:
      - name: NginxModuleOtelMaxQueueSize
        value: "4096"
      image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:latest
    # sdk:
    #   image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-sdk:latest

  opAMPBridge:
    enabled: false
    addReportingLabel: true

# Глобальные переменные чарта
global:
  folder_id: ""
  monium_api_key: ""
  otel_enabled: "true"
