opentelemetry-kube-stack:
  clusterName: sausage-store-cluster

  opentelemetry-operator:
    enabled: true
    manager:
      extraArgs:
        - --enable-go-instrumentation=true
        - --enable-nginx-instrumentation=true

  rbac: # k8sattributes
    create: true

  commonEnv:
    - name: MONIUM_API_KEY
      valueFrom:
        secretKeyRef:
          name: monium-secret
          key: api-key
    - name: MONIUM_FOLDER_ID
      valueFrom:
        secretKeyRef:
          name: monium-secret
          key: folder-id

  collectors:
    # Агент (DaemonSet) на каждой ноде кластера
    agent:
      enabled: true
      mode: daemonset
      fullnameOverride: "otel-agent"
      presets:
        logsCollection: # доступ к лог-файлам [/var/log/pods/*/*/*.log]
          enabled: true
          includeCollectorLogs: false # не собирать логи OTel
        hostMetrics:
          enabled: true # метрики CPU/RAM нод 
        kubernetesAttributes:
          enabled: true # k8s_attributes
          extractAllPodLabels: true
          extractAllPodAnnotations: true
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
      image:
        repository: otel/opentelemetry-collector-contrib
        tag: latest 
      service:
        enabled: true
        type: ClusterIP
        internalTrafficPolicy: Local
      # Пробрасываем порты на IP ноды
      hostNetwork: false
      ports:
        - name: otlp-grpc
          port: 4317
          #hostPort: 4317
          appProtocol: grpc
          protocol: TCP
        - name: otlp-http
          port: 4318
          #hostPort: 4318
          appProtocol: http
          protocol: TCP
        - name: syslog-udp
          port: 54527
          #hostPort: 54527
          protocol: UDP
      config:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
              http: # для Go
                endpoint: "0.0.0.0:4318"
          syslog:
            udp:
              listen_address: "0.0.0.0:54527"
            protocol: rfc3164 # rfc3164 стандартный Syslog. rfc5424
            operators: # nginx шлёт JSON 
              - type: json_parser
                parse_from: body
                parse_to: attributes
                onError: drop
          filelog/nginx:
            include: [/var/log/pods/*/*/*.log]
            exclude: [/var/log/pods/otel_*/*/*.log]
            include_file_path: true
            start_at: end
            operators:
              - type: container
              - type: regex_parser
                id: nginx-parser
                regex: 'trace_id=(?P<trace_id>[a-f0-9]+)\s+span_id=(?P<span_id>[a-f0-9]+)\s+request_id=(?P<request_id>[a-f0-9-]+)'
                parse_from: body
                if: 'body contains "trace_id="'
                on_error: drop
        processors:
          memory_limiter:
            check_interval: 1s
            limit_percentage: 85
            spike_limit_percentage: 10
          batch:
            send_batch_size: 8192
            timeout: 2s
          transform/common:
            log_statements:
              - context: log
                statements:
                  - set(log.trace_id, TraceID(log.attributes["trace_id"])) where log.attributes["trace_id"] != nil
                  - set(log.span_id, SpanID(log.attributes["span_id"])) where log.attributes["span_id"] != nil
                  - set(resource.attributes["service.name"], Concat([log.attributes["k8s.container.name"], log.attributes["k8s.namespace.name"]], "."))
                    where log.attributes["k8s.container.name"] != nil and log.attributes["k8s.namespace.name"] != nil
                  - delete_matching_keys(log.attributes, "^(trace_id|span_id)$")
        exporters:
          # Агент пересылает данные на шлюз (gateway) внутри кластера
          otlp_grpc:
            endpoint: "otel-gateway-collector:4317"
            tls:
              insecure: true
          debug:
            verbosity: normal
        service:
          pipelines:
            metrics:
              receivers: [otlp]
              processors: [memory_limiter, batch]
              exporters: [otlp_grpc]
            traces:
              receivers: [otlp]
              processors: [memory_limiter, batch]
              exporters: [otlp_grpc]
            logs:
              receivers: [otlp, syslog, filelog/nginx]
              processors: [memory_limiter, transform/common, batch]
              exporters: [otlp_grpc]
    # Центральный шлюз (Deployment) для отправки в облако
    gateway:
      enabled: true
      mode: deployment
      fullnameOverride: "otel-gateway"
      presets: # сбора агрегированных данных о состоянии всего кластера
        clusterMetrics: 
          enabled: true
      replicaCount: 4 # по 1й на каждую зону
      autoscaling:
        enabled: true
        minReplicas: 4
        maxReplicas: 8
        targetCPUUtilizationPercentage: 80
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
      # мягкое ограничение по зонам
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway 
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: "otel-gateway"
      # жёсткое ограничение по нодам - 1 под на 1 ноду
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: "otel-gateway"
            topologyKey: "kubernetes.io/hostname"
      env:
        - name: MONIUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: monium-secret
              key: api-key
        - name: MONIUM_FOLDER_ID
          valueFrom:
            secretKeyRef:
              name: monium-secret
              key: folder-id
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      config:
        extensions:
          health_check:
            endpoint: 0.0.0.0:13133
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
              http:
                endpoint: "0.0.0.0:4318"
        processors:
          batch:
            send_batch_size: 4096
            send_batch_max_size: 8192
            timeout: 10s
        exporters:
          # Шлюз авторизуется и отправляет данные в Yandex Monitoring (Monium)
          otlp_grpc/monium:
            endpoint: "ingest.monium.yandex.cloud:443"
            compression: zstd
            headers:
              Authorization: "Api-Key ${env:MONIUM_API_KEY}"
              x-monium-project: "folder__${env:MONIUM_FOLDER_ID}"
            sending_queue:
              enabled: true
            # Настройки повторных попыток при ошибках
            retry_on_failure:
              enabled: true
              initial_interval: 5s
              max_interval: 30s
              max_elapsed_time: 300s
          debug:
            verbosity: normal
        service:
          extensions: [health_check]
          pipelines:
            metrics:
              receivers: [ otlp ]
              processors: [ batch ]
              exporters: [ otlp_grpc/monium ]
            traces:
              receivers: [ otlp ]
              processors: [ batch ]
              exporters: [ otlp_grpc/monium ]
            logs:
              receivers: [ otlp ]
              processors: [ batch ]
              exporters: [ otlp_grpc/monium ]
        # Телеметрия самого OTel Collector
        telemetry:
          logs:
            level: warn  # debug | info | warn | error
          metrics:
            level: normal  # none | basic | normal | detailed
            readers:
              - periodic:
                  interval: 60000
                  exporter:
                    otlp:
                      protocol: http/protobuf
                      endpoint: http://${env:MY_POD_IP}:4318

  instrumentation:
    enabled: true
    name: "sausage-store-instrumentation"
    exporter:
      endpoint: "http://otel-agent-collector.otel.svc.cluster.local:4317"
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: "grpc"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_BSP_MAX_QUEUE_SIZE
        value: "8192"
      - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
        value: "2048"
      - name: OTEL_BSP_SCHEDULE_DELAY
        value: "500"
    propagators:
      - tracecontext
      - baggage
    resource:
      resourceAttributes:
        service.name: "sausage-store"
        deployment.environment: "production"
        project: "folder__{{ .Values.global.folder_id }}"
    java:
      image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    go: # https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/docs/configuration.md
      env:
        - name: OTEL_LOG_LEVEL
          value: "info"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-agent-collector.otel.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: "grpc"
        - name: OTEL_GO_AUTO_INCLUDE_DB_STATEMENT
          value: "true"
        - name: OTEL_GO_AUTO_PARSE_DB_STATEMENT
          value: "true"
      image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest
    nginx:
      env:
        - name: OTEL_LOG_LEVEL
          value: "info"
      attrs:
      - name: NginxModuleOtelMaxQueueSize
        value: "4096"
      image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:latest
    # sdk:
    #   image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-sdk:latest

  opAMPBridge:
    enabled: false
    addReportingLabel: true

# Глобальные переменные чарта
global:
  folder_id: ""
  monium_api_key: ""
  otel_enabled: "true"
