apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sausage-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repo_url | quote }}
    path: "yc/sausage-store"
    targetRevision: "master"
    helm:
      releaseName: sausage-store
      valueFiles:
        - "values.yaml"
      values: |
        global:
          gitlab_registry: {{ .Values.global.gitlab_registry | quote }}
          gitlab_user: {{ .Values.global.gitlab_user | quote }}
          gitlab_token: {{ .Values.global.gitlab_token | quote }}
        sausage-store:
          backend:
            extraEnv:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dspring.cloud.vault.enabled=false -Dspring.config.import=optional:vault://kv/sausage-store"
            envFrom:
              - secretRef:
                  name: "sausage-kv-secret"
          lockbox:
            sa_id: {{ .Values.global.sa_id | quote }}
            secret_id: {{ .Values.global.lockbox_secret_id | quote }}
          ingress:
            gwin_ip: {{ .Values.global.gwin_ip | quote }}
            gwin_sg: {{ .Values.global.gwin_sg | quote }}
            certificate_id: {{ .Values.global.certificate_id | quote }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "sausage-store"
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
