apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: yandex-lockbox
  namespace: sausage-store
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: auth
          namespace: external-secrets
