apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: sausage-store-kv
  namespace: sausage-store
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: auth
          namespace: external-secrets
