apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: yandex-lockbox
  namespace: sausage-store
spec:
  provider:
    yandexlockbox:
      auth: {}
#        serviceAccountID: {{ .Values.global.sa_id | quote }}
