{{- if and .Values.global.gitlab_user .Values.global.gitlab_token -}}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.global.gitlab_registry (printf "%s:%s" .Values.global.gitlab_user .Values.global.gitlab_token | b64enc) | quote }}
{{- end }}
