{{- if .Values.global.otel_enabled }}
apiVersion: monitoring.yandex.cloud/v1alpha1
kind: MonitoringAlert
metadata:
  name: {{ include "sausage-store.vigilia.site" . }}-errors
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  query: "sum(http_req_failed{service='{{ include "sausage-store.vigilia.site" . }}'})"
  condition:
    threshold: 3
    comparison: "greater_than"
  notificationChannels:
    - {{ .Values.monitoring.notificationChannelId }}
{{- end }}
